theme: jekyll-theme-minimal
title: Cristiano Miranda's ePortfolio
description: An ePortfolio containing enhancements to the various assignments and projects made during the SNHU Computer Science Program.  
